name: Deploy WordPress Plugin

on: [workflow_dispatch]
  # push:
  #   branches:
  #     - yuvayana

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ./

      - name: Build React app
        run: npm run build:free
        working-directory: ./

      - name: Set plugin version for Free
        run: |
          sed -i 's/{{VERSION}}/1.0.0/' acadlix.php
          sed -i 's/{{VERSION}}/1.0.0/' languages/Common/acadlix.pot

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer
        run: |
          composer install --no-dev --optimize-autoloader
        working-directory: ./

      - name: Zip the plugin
        run: |
          zip -r plugin.zip . -x "node_modules/*" \
                              -x ".gitignore" \
                              -x ".git/*" \
                              -x ".github/*" \
                              -x "src/*" \
                              -x "package-lock.json" \
                              -x "package.json" \
                              -x "README.md" \
                              -x "composer.json" \
                              -x "composer.lock" \
                              -x "webpack.config.js" \
                              -x "test.json" \
                              -x "api.txt" \
                              -x jsconfig.json \
                              -x handle-dev-server.sh \
        working-directory: ./

      - name: Upload ZIP to server
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$EC2_SSH_KEY" > private_key
          chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key plugin.zip bitnami@$EC2_HOST:/home/bitnami/

      - name: Deploy to WordPress
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$EC2_SSH_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key bitnami@$EC2_HOST << 'EOF'
            unzip -o /home/bitnami/plugin.zip -d /home/bitnami/stack/wordpress/wp-content/plugins/acadlix
            rm /home/bitnami/plugin.zip
          EOF
